apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nitro-repo-chart.fullname" . }}-config
  labels:
    {{- include "nitro-repo-chart.labels" . | nindent 4 }}
data:
  nitro_repo.toml: |
    [site]
    host = "0.0.0.0"
    port = {{ .Values.service.port }}

    [site.database]
    url = "${DATABASE_URL}"
