mode = "Debug"
suggested_local_storage_path = "/data/storages"

[database]
user = "nitro"
password = "nitro"
database = "nitro_repo"
host = "postgres"
port = 5432

[sessions]
lifespan = 86400
cleanup_interval = 3600
database_location = "/data/sessions.redb"

[site]
app_url = "https://nitro.sudoers.dev"


[security]
allow_basic_without_tokens = true

[security.password_rules]
min_length = 12
require_uppercase = false
require_lowercase = true
require_number = false
require_symbol = false

  # [security.sso]
  # enabled = true
  # login_path = "/api/user/sso/login"
  # login_button_text = "Sign in with Cloudflare"
  # provider_login_url = "https://repo.sudoers.dev/cdn-cgi/access/login"
  # provider_redirect_param = "redirect_url"
  # username_header = "CF-Access-Authenticated-User-Email"
  # email_header = "CF-Access-Authenticated-User-Email"
  # display_name_header = "CF-Access-Authenticated-User-Name"
  # auto_create_users = true


[log.levels]
default = "Debug"
[log.levels.others]
"nitro_repo" = "Debug"
"nr_core" = "Debug"
"nr_storage" = "Debug"
"sqlx" = "Debug"
"pg_extended_sqlx_queries" = "Debug"
"h2" = "Debug"
"tower" = "Debug"
"tonic" = "Debug"
"hyper_util" = "Debug"
