services:
  nitro-docs:
    image: nginx:alpine
    container_name: nitro-docs
    restart: unless-stopped
    volumes:
      - ./docs/.vitepress/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nitro-docs.rule=Host(`nitro-docs.sudoers.dev`)"
      - "traefik.http.services.nitro-docs.loadbalancer.server.port=80"
      - "traefik.http.routers.nitro-docs.entrypoints=https"
      - "traefik.http.routers.nitro-docs.tls.certresolver=letsencrypt"
    network_mode: "bridge"

networks:
  default:
    external: true
    name: bridge
